### ISSUE TITLE
Submitting the form

### ISSUE THREAD

**Issue by mrw4n** [niklasvh/feedback.js#1]
Can you explain how can we actually submit the form and send the collected data to a server?

I mean how can i send the image and the issue description?

**Comment by niklasvh** [comment]
As mentioned in the readme, its still work in progress, i.e. not complete. The form will be sent using XHR with the image sent as a base64 encoded string. Will come in an adapter format, so you will be able to easily write your own adapter as well.

**Comment by maximz** [comment]
In other words, when feedback.js is released, we'll just pass a callback function that will be executed once form entry is completed?

**Comment by niklasvh** [comment]
Currently planning on having a default XHR adapter, to which you can provide the url to send the data to. Alternatively, you could write your own adapter, which would work similarly to a callback function where you have the option to do what you want with the gathered data.

**Comment by roguemonkey** [comment]
Just wanted to ping on this to manifest my interest in this feature and the whole project in general. It would be invaluable to a lot of developers to be able to include a way for users to report bugs, and we all know an image is worth a thousand words ;)

**Comment by niklasvh** [comment]
I'll try and get a preliminary version up asap, just been distracted with some other projects for the past week.

**Comment by radomirml** [comment]
Here's a simple customization of feedback.js that uploads screenshot and feedback message to BugDigger service:
http://radomirml.com/2012/08/28/feedback-js-upload-screenshot-to-bugdigger

**Comment by roguemonkey** [comment]
Wow, very nice. I'll check out when time permits to see how integration 

## with my projects would work. Thank you very much for making this available!

Alex

**Comment by cbrulak** [comment]
check out my pull request; https://github.com/niklasvh/feedback.js/pull/5

feedback is always appreciated. 

or see my repo here: https://github.com/amaabca/feedback.js

**Comment by apatni** [comment]
Hi,

I'm new to this and want to use same feature on my site. Here are some couple of things which i want to know
1. Can I use send feedback button as icon or a link in my menu bar or under sub menu if yes then can u please show me the example.
2. Also i would like to save the image in my local folder after highlight / blackout is it possible?

I search whole web and couldn't fount any documentation or easy example who can tell me how to implement it easily.

Sorry to ask you silly question but i like this function and want to use it some where on my web :).

Thank you, :)

Regards,
Ankit

**Comment by apatni** [comment]
is there anyway to capture flash object or SVG ??? I have some flash object on my page which i want to capture in screenshot.

**Comment by niklasvh** [comment]
See #6
