### ISSUE TITLE
License of feedback.js?

### ISSUE THREAD

**Issue by hyandell** [niklasvh/feedback.js#3]
I'm wondering what the license of feedback is?

I looked in the expected place at the source header of the files and didn't see anything, so I'm not sure the conditions of using this.

**Comment by niklasvh** [comment]
It'll be under MIT license. Reason there isn't the information there yet is as it isn't fully functional/usable yet.

**Comment by hyandell** [comment]
Thanks Niklas.

Is your advice that people shouldn't use this until you put a license on it?

If not, having an MIT license on there would definitely be a happiness.

**Comment by niklasvh** [comment]
Well it doesn't work as it is (doesn't send any data, and lot of IE fixes still to do) so I don't see much point in using it yet (you'd need to code stuff to get it working anyway)

You are of course free to use it now, but I'd recommend not to unless you are in a critical hurry and want to finish the remaining functionality/bugs yourself.

**Comment by hyandell** [comment]
Cool - thanks for all the info :)
