### ISSUE TITLE
Second capture does not work

### ISSUE THREAD

**Issue by siddarthvader** [niklasvh/feedback.js#34]
If you tried to capture second feedback without refreshing the page it does not show the latest feedback instead of it i keep showing the old feedback.

**Comment by Strae** [comment]
I can confirm this bug too; No errors on js console but the screenshot data is the same for the 2° capture

**Comment by siddarthvader** [comment]
sir, i have worked it out, if you want me to share the code i can, thanks :)

**Comment by Strae** [comment]
Yeah, a gist or a pull request woul be apprecciated!

**Comment by siddarthvader** [comment]
ok. sir, try commenting out the lines i have shown in screenshot, it will work, actually its not dumping the old data and then there is a check init  if data is null or not (high lighted section). works fine.
![domfeedback](https://cloud.githubusercontent.com/assets/7977737/4302370/55f0885e-3e59-11e4-91d6-59c0482bd801.png)

**Comment by siddarthvader** [comment]
actually sir I am new to github, so i dont how how to upload code, i have tried this way and i dont think it is a good way, kindly enlighten me !!!

**Comment by Strae** [comment]
For sharing quick snippets of code, you can use [github's gist](https://gist.github.com/) (you can find the link in the header, next to the "explore" link)

Else, the best way would be to fork the main repository from niklasvh, add your edit, then commit, push (to your fork!) and to make a pull request to the main repository (that niklasvh should accept or deny).. 
If the main author dont accept your edits, you allways have your fork to share with others...
ye im not good with explanation ;)

Thanks for your code, youre great!

**Comment by Strae** [comment]
For example, a gist for your edit would [look like this](https://gist.github.com/Strae/9c052fe6e001be7779ac)

**Comment by hipointinc** [comment]
If you are having issues with the form data also caching just do the same for 

window.Feedback.Form.prototype.data which is on line 374 i believe.
