### ISSUE TITLE
Great, but doesnt work with iframe :(

### ISSUE THREAD

**Issue by piyey** [niklasvh/feedback.js#37]
I recently found this great library and immediately got to do something with it, finishing my implementation with some modifications I discovered that you can not take screenshot on a website with iframe. Can you guide me how to achieve this? 

Thank you for your great contribution.

**Comment by niklasvh** [comment]
This library hasn't been updated in years. I've had it on my backlog for a very long time to start actively maintaining this project, but as it currently is, I wouldn't recommend using this project.

The underlying library doing the rendering of the page is html2canvas, and until recently it didn't support rendering iframe content. The 0.5 version of html2canvas will support rendering iframes

**Comment by piyey** [comment]
> I wouldn't recommend using this project.

So, what would you recommend to use? :+1: 

Regards!!!
